### ISSUE TITLE
Future of this extension

### ISSUE THREAD

**Issue by joneshf** [mvakula/vscode-purty#4]
I'm thinking about [how to support editor integration better][editor]. Releases have started up again with `purty` (as there's work to do again). But, there's a bit of drift between a new version being released and this extension being updated. Currently, a [PR to update this extension to the 4.x.x series][PR] has been open for two weeks. I'm not wanting to strong arm you into changing anything or increasing your burden, but I'd like to try and support downstream consumers of `purty` however I can.

The state of things is that any code changed _should_ be released every Tuesday at 9AM Pacific. I'm more than happy to figure some way to notify this project when there's a breaking release.

I'm also more than happy to maintain this extension (or at least the spirit of it) in the `purty` repo. The idea there being that the extension can stay more in sync with releases that way.

Finally, I'm also wanting to see how the main PS extension thinks about integration with `purty`. It might be that we can move most of the burden off of this extension by pushing further up stream. I'll open an issue there shortly.

@mvakula, What are your thoughts?

[editor]: https://gitlab.com/joneshf/purty/issues/124
[pr]: https://github.com/mvakula/vscode-purty/pull/1

**Comment by mvakula** [comment]
Sorry, I'll take a look how to update this extension to match updated purty. I'm travelling at the moment, so I'll get back to you soon.

**Comment by mvakula** [comment]
I updated and published new version which works with the latest purty. Let's see how [this](https://github.com/nwolverson/vscode-language-purescript/issues/10) evolves.

> The state of things is that any code changed should be released every Tuesday at 9AM Pacific. I'm more than happy to figure some way to notify this project when there's a breaking release.

You can ping me in functional programming Slack if I don't in the future if I don't react here fast enough.

**Comment by joneshf** [comment]
Awesome!
