### ISSUE TITLE
configure purty executable path

### ISSUE THREAD

**Issue by shmish111** [mvakula/vscode-purty#9]
Hi, I would like a workspace setting for the path to my purty executable (I use nix for my project and I want to use whatever purty is in my nix project).

**Comment by mvakula** [comment]
@shmish111 feel free to contribute 😉 
The code is only 80 lines and heres the function `findLocalPurty` https://github.com/mvakula/vscode-purty/blob/master/extension.js#L54

**Comment by shmish111** [comment]
lol, I was hoping you wouldn't say that 😄

**Comment by mvakula** [comment]
haha😄 I might do this in couple of weeks but I don't personally have use case for this so if I'm busy.. 😄

**Comment by richard-uk1** [comment]
PR #10 closes this.
